### ISSUE TITLE
calculator resizing issue

### ISSUE THREAD

**Issue by Vishnu-C-Prasad** [Sreekuttykj/Calculator#3]
calculator resizing when entering numbers
issue on claculate.js
on function 'check length & disable buttons '

**Comment by Sreekuttykj** [comment]
Got it 
fixing it soon 
you can also contribute on it

**Comment by Vishnu-C-Prasad** [comment]
ok i am pulling a branch now 
it fixes this issue

**Comment by Sreekuttykj** [comment]
Ok

**Comment by Sreekuttykj** [comment]
thank you

issue fixed
